Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/IndentHash:
  EnforcedStyle: consistent

Style/AlignHash:
  EnforcedColonStyle: table

Style/ModuleFunction:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
    EnforcedStyle: "double_quotes"

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Enabled: false

