Layout/IndentHash:
  EnforcedStyle: consistent

#Style/ClassAndModuleChildren:
#  EnforcedStyle: disabled

Style/StringLiterals:
    EnforcedStyle: "double_quotes"

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Enabled: false
